version: '3.8'

services:
  # Main Application
  app:
    build: .
    ports:
      - "3003:3003"
    environment:
      # Database (SQLite)
      DATABASE_URL: file:./data/database.db

      # NextAuth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-super-secret-key-change-this-in-production-2024}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3003}

      # Swiss AI Platform API Key
      SWISS_AI_PLATFORM_API_KEY: ${SWISS_AI_PLATFORM_API_KEY:-your-swiss-ai-api-key-here}

      # Apertus Configuration
      APERTUS_BASE_URL: ${APERTUS_BASE_URL:-https://api.swisscom.com/layer/swiss-ai-weeks/apertus-70b/v1}
      APERTUS_MODEL_ID: ${APERTUS_MODEL_ID:-swiss-ai/Apertus-70B}
      APERTUS_MAX_RETRIES: ${APERTUS_MAX_RETRIES:-5}
      APERTUS_BASE_DELAY: ${APERTUS_BASE_DELAY:-1.0}
      APERTUS_MAX_DELAY: ${APERTUS_MAX_DELAY:-16}
      APERTUS_PRECALL_SLEEP: ${APERTUS_PRECALL_SLEEP:-0.5}

      # Production settings
      NODE_ENV: production
    volumes:
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    init: true

volumes:
  sqlite_data:

networks:
  default:
    name: ramona-network